### PR TITLE
fix: fixed Not Authorized page style

### LINKED ISSUE #423: fix: style "not authorized" admin view
snip20190105_3

### PR DESCRIPTION
**Pull request by aloks98**
Changed Not Authorized view and access from one line to a page beautified with link to homepage

BREAKING CHANGE:
None

## Related Issue
Closes #423

## Your solution
Added an image with proper css and a link to homepage

## How Has This Been Tested?
NA

### CODE REVIEW

**Comment by Ashu96** [comment]
Hey @aloks98 good work :+1: 

Could you please attach a screenshot of the change that you have made? It would help us in reviewing, thanks.

**Comment by aloks98** [comment]
@Ashu96 here is a ss
webiny

File: packages/app-security/src/admin/plugins/secureRouteError.tsx [hunk 1]
```diff
@@ -9,10 +18,13 @@ const plugin: SecureRouteErrorPlugin = {
...
         return (
-            <>
+            <div className={notAuthCss}>    
                 <Helmet title={"Not authorized"} />
-                <span>You are not authorized to access this route.</span>
-            </>
+                <img src={authErrorImg} alt="Not Authorized" width="40%"/>
+                <p>You are not authorized to view this route.</p>
+                <p>Please contact your administrator to request access.</p>
+                <a href="/">Take me back.</a>
```
Comment (Ashu96) [inline packages/app-security/src/admin/plugins/secureRouteError.tsx:26]: Please use `Link` component from `@webiny/react-router` instead of `a` tag.

File: packages/app-security/src/admin/plugins/secureRouteError.tsx [hunk 2]
```diff
@@ -9,10 +18,13 @@ const plugin: SecureRouteErrorPlugin = {
     name: "secure-route-error",
     render() {
         return (
-            <>
+            <div className={notAuthCss}>    
                 <Helmet title={"Not authorized"} />
-                <span>You are not authorized to access this route.</span>
-            </>
+                <img src={authErrorImg} alt="Not Authorized" width="40%"/>
+                <p>You are not authorized to view this route.</p>
```
Comment (Ashu96) [inline packages/app-security/src/admin/plugins/secureRouteError.tsx:24]: Please use `Typography` component from `@webiny/ui/Typography` package instead. For example,

```js
<Typography use={"body1"} className={...}>               
     You are not authorized to access this route.
 </Typography>
```

File: packages/app-security/src/admin/plugins/secureRouteError.tsx [hunk 3]
```diff
@@ -9,10 +18,13 @@ const plugin: SecureRouteErrorPlugin = {
     name: "secure-route-error",
     render() {
         return (
-            <>
+            <div className={notAuthCss}>    
                 <Helmet title={"Not authorized"} />
-                <span>You are not authorized to access this route.</span>
-            </>
+                <img src={authErrorImg} alt="Not Authorized" width="40%"/>
```
Comment (Ashu96) [inline packages/app-security/src/admin/plugins/secureRouteError.tsx:23]: Please remove the inline style here. We avoid using inline style as much possible. You can use `CSS` class or even [styled component](https://emotion.sh/docs/styled)

File: packages/app-security/src/components/SecureRoute.tsx [hunk 4]
```diff
@@ -19,7 +31,15 @@ export default ({
 
     const plugin = getPlugin<SecureRouteErrorPlugin>("secure-route-error");
     if (!plugin) {
-        return <span>You are not authorized to view this route.</span>;
+        return (
+            <div className={notAuthCss}>
```
Comment (Ashu96) [inline packages/app-security/src/components/SecureRoute.tsx:35]: Instead of duplicating the code, please try extracting it into a reusable component.

**Review by Ashu96 — CHANGES_REQUESTED** [review]
Good work @aloks98  :+1: 

I've left a few comments, please check them out. Nothing major just minor stuff about the convention.

In general, also try making the view look more similar to the original design attached to the issue.
For example, 

1. Make the art image smaller, about `192px` in width.
2. Change the text color to theme color i.e `color: var(--mdc-theme-text-primary-on-background)`

**Comment by aloks98** [comment]
sure, I will commit the changes by tonight.

**Comment by aloks98** [comment]
@Ashu96 can you check the changes I made? Tell me if I went wrong anywhere, I will fix that asap.

**Comment by Ashu96** [comment]
Good work @aloks98 :+1: 
Can you please attach the screenshot of the updated view? It'll help me with the review. Thanks.

**Comment by aloks98** [comment]
webiny
@Ashu96 here you go

**Comment by Ashu96** [comment]
> webiny
> @Ashu96 here you go

@aloks98 Can you please vertically align the `NotAuthorizedError` view. Like we've in the original design :slightly_smiling_face:

**Comment by aloks98** [comment]
@Ashu96 Please check
Screenshot from 2020-10-07 14-44-33

File: packages/app-security/src/components/NotAuthorizedError.tsx [hunk 5]
```diff
@@ -0,0 +1,63 @@
...
+const ContentWrapper = styled("div")({
+    display: "block",
+    paddingTop: "15%",
+    textAlign: "center",
+    margin: "auto"
+});
+
+const styles = {
+    authErrorImgStyle: css({
+        width: "192px"
```
Comment (Ashu96) [inline packages/app-security/src/components/NotAuthorizedError.tsx:18]: I would add some bottom spacing here. For example, `padding-bottom: "24px"`

File: packages/app-security/src/components/NotAuthorizedError.tsx [hunk 6]
```diff
@@ -0,0 +1,63 @@
...
+        color: "var(--mdc-theme-text-primary-on-background)"
+    }),
+    linkStyle: css({
+        textDecoration: "none",
+        "&:hover": {
+            textDecoration: "none"
+        }
+    }),
+    divStyles: css({
+        padding: "5px"
```
Comment (Ashu96) [inline packages/app-security/src/components/NotAuthorizedError.tsx:30]: Please don't add bottom spacing between each line of text. It's a single paragraph of text should look like that.

File: packages/app-security/src/components/NotAuthorizedError.tsx [hunk 7]
```diff
@@ -0,0 +1,63 @@
...
+
+const NotAuthorizedError = () => {
+    return (
+        <ContentWrapper>
+            <Helmet title={"Not authorized"} />
+            <div className={styles.divStyles}>
+                <img className={styles.authErrorImgStyle} src={authErrorImg} alt="Not Authorized" />
+            </div>
+
+            <div className={styles.divStyles}>
```
Comment (Ashu96) [inline packages/app-security/src/components/NotAuthorizedError.tsx:42]: I think there is no need to wrap each tag/element in a `div`. What do you think? :slightly_smiling_face:

Comment (aloks98) [reply packages/app-security/src/components/NotAuthorizedError.tsx:42]: I actually added that coz the `<Typography>` package renders `<span>` instead of `<div>`. And if we are using <div> it all comes on the same line. Is there any way to fix that?

File: packages/app-security/src/components/NotAuthorizedError.tsx (hunk 6 above)
Comment (aloks98) [reply packages/app-security/src/components/NotAuthorizedError.tsx:30]: Okay will remove, I added it coz it looked good

File: packages/app-security/src/components/NotAuthorizedError.tsx (hunk 5 above)
Comment (aloks98) [reply packages/app-security/src/components/NotAuthorizedError.tsx:18]: Okay I will add that

File: packages/app-security/src/components/NotAuthorizedError.tsx (hunk 7 above)
Comment (aloks98) [reply packages/app-security/src/components/NotAuthorizedError.tsx:42]: Screenshot from 2020-10-07 20-43-49
Please look into this.

Comment (Ashu96) [reply packages/app-security/src/components/NotAuthorizedError.tsx:42]: There are multiple ways to fix that but I'll go with the simplest i.e apply `display: block` CSS property on the `Typography` component. :slightly_smiling_face:

**Comment by aloks98** [comment]
Screenshot from 2020-10-08 16-31-48
@Ashu96 please review :)

**Review by Ashu96 — CHANGES_REQUESTED** [review]
Well done @aloks98 :+1: 
The changes look great visually :100:  

But, there are some checks falling. Could you please fix the prettier error? :slightly_smiling_face:

**Comment by aloks98** [comment]
Done :100:

**Review by Ashu96 — APPROVED** [review]
Thanks for your contribution @aloks98 :+1: 

We'll merge it soon :slightly_smiling_face:
