### PR TITLE
Fix: `limit` param in list content model query not working

### LINKED ISSUE #983: Headless CMS - `limit`param in list content model query not working
## This is:
- Bug

## Specifications

  - version: 4.x
  - OS: Ubuntu 18.04 LTS
  - Browser: Chrome 83

## Expected Behavior
Should return the content limit to the number specified by `limit` param in GQL query

The image below shows that the content model has entries
limit_result

## Actual Behavior
Returning empty array i.e no data with `limit` param set in GQL query

image_empty

## Steps to Reproduce the Problem
1. Visit GQL playground for manage API
2. Try running a GQL query to list content entries for a content model with `limit` param

### PR DESCRIPTION
**Pull request by Ashu96**
## Related Issue
Closes #983 
Headless CMS - `limit` param in list content model query not working 

## Your solution

- Add `model` in query
- Scale `limit` by locales for MANAGE API

## How Has This Been Tested?
Manually, using GraphQL playground for `manage` API

## Screenshots:
image

### CODE REVIEW

File: packages/api-headless-cms/src/content/plugins/utils/findEntries.ts [hunk 1]
```diff
@@ -52,6 +52,15 @@ export default async function findEntries<T = CmsContext>({
         query.locale = context.cms.locale.id;
     }
 
+    // For `manage` API we always want to multiple `limit` by available locales
```
Comment (doitadrian) [inline packages/api-headless-cms/src/content/plugins/utils/findEntries.ts:55]: "multiple" => "multiply" :)

Comment (doitadrian) [reply packages/api-headless-cms/src/content/plugins/utils/findEntries.ts:55]: BTW @Ashu96, please add a bit more description here so that it's clear why exactly we need this.

File: packages/api-headless-cms/__tests__/limitListContentEntries.test.js [hunk 2]
```diff
@@ -0,0 +1,60 @@
...
+        const book1 = await books.create(mocks.book1);
+        const book2 = await books.create(mocks.book2);
+        const book3 = await books.create(mocks.book3);
+        const book4 = await books.create(mocks.book4);
+
+        const bookList = await books.list({});
+
+        expect(bookList.length).toBe(4);
+
+        // TODO: Should be clean up the entries
```
Comment (doitadrian) [inline packages/api-headless-cms/__tests__/limitListContentEntries.test.js:32]: Instantiate `useContentHandler` in each test.

File: packages/api-headless-cms/__tests__/limitListContentEntries.test.js [hunk 3]
```diff
@@ -0,0 +1,60 @@
...
+        const books = await content("book");
+
+        const book1 = await books.create(mocks.book1);
+        const book2 = await books.create(mocks.book2);
+        const book3 = await books.create(mocks.book3);
+        const book4 = await books.create(mocks.book4);
+
+        const bookList = await books.list({ limit: 2 });
+
+        expect(bookList.length).toBe(2);
```
Comment (doitadrian) [inline packages/api-headless-cms/__tests__/limitListContentEntries.test.js:52]: Please just make a simple content-check.
