### PR TITLE
Fix Website React Application Upload

### LINKED ISSUE #1701: Error on new deployment (V5.8) creating / editing pages.
## This is:
- Bug

## Specifications

  - version: 5.8

## Expected Behavior
View static page loaded from s3

## Actual Behavior
In a new Webiny deployment, when editing and pages are not displayed because the rendering lambda fails and therefore the pages are not saved in s3

## Steps to Reproduce the Problem
1. Install clean version of webiny 5.8
2. Try to view page
3. Edit or create new pages

## Detailed Description
This is the log generated by the render lambda.

```
2021-06-08T00:34:59.113Z	71e560ea-6f2d-4968-86c1-300ee270e17b	INFO	"Evaluation failed: TypeError: window.getApolloState is not a function\n    at __puppeteer_evaluation_script__:3:19"
```

And also this
```
2021-06-08T00:42:03.369Z	e487cecc-52c9-4555-b893-4b9501bf56fa	INFO	An error occurred while prerendering... Error: Evaluation failed: TypeError: window.getApolloState is not a function
    at __puppeteer_evaluation_script__:3:19
    at ExecutionContext._evaluateInternal (/opt/nodejs/node_modules/puppeteer-core/lib/cjs/puppeteer/common/ExecutionContext.js:217:19)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async ExecutionContext.evaluate (/opt/nodejs/node_modules/puppeteer-core/lib/cjs/puppeteer/common/ExecutionContext.js:106:16)
    at async defaultRenderUrlFunction (/var/task/handler.js:7076:23)
    at async _default (/var/task/handler.js:6955:18)
    at async handle (/var/task/handler.js:4534:25)
    at async /var/task/handler.js:5457:28
```

Thanks

### PR DESCRIPTION
**Pull request by adrians5j**
## Changes
In order to resolve the reported issue, we ensured no backslashes are used ("\\"), by replacing them with forward slashes.

Closes #1701 

## How Has This Been Tested?
Manual testing.

## Documentation
Changelog.

### CODE REVIEW

File: packages/cli-plugin-deploy-pulumi/utils/aws/uploadFolderToS3.js [hunk 1]
```diff
@@ -25,7 +25,10 @@ module.exports = async ({ path: root, bucket, onFileUploadSuccess, onFileUploadE
         const promises = [];
         for (let j = 0; j < chunk.length; j++) {
             const path = chunk[j];
-            const key = relative(root, path);
+
+            // We also replace "\" with "/", which can occur on Windows' CMD or Powershell.
+            // https://github.com/webiny/webiny-js/issues/1701#issuecomment-860123555
+            const key = relative(root, path).replace("\\", "/");
```
Comment (arepageek) [inline packages/cli-plugin-deploy-pulumi/utils/aws/uploadFolderToS3.js:31]: Hello, remember to update it with 

`.replace(/\\/g, "/");`

Comment (adrians5j) [reply packages/cli-plugin-deploy-pulumi/utils/aws/uploadFolderToS3.js:31]: Yup, already in `v5` release branch:
https://github.com/webiny/webiny-js/blob/v5/packages/cli-plugin-deploy-pulumi/utils/aws/uploadFolderToS3.js#L31

But in any case, thanks for the tip :)
