### PR TITLE
Fix/environment incorrect url

### LINKED ISSUE #936: Headless CMS - handle incorrect API URLs
Accessing an invalid URL, like the following...
```https://dugilt40hnfag.cloudfront.net/cms/reXYZad/5ecbedb4e78b2b00082b8b63```

...causes the following error to be thrown:
image

### PR DESCRIPTION
**Pull request by EmilK15**
## Related Issue

Closes #936 

## Your solution
Added try/catch block around the logic that would try to grab environments based on the alias name provided.
Wrote test case to make sure this behavior is enforced and checked for.

## How Has This Been Tested?
Looked at urls with incorrect aliases to see if error message was updated

## Screenshots (if relevant):
image
image

### CODE REVIEW

File: packages/api-headless-cms/src/content/plugins/models.ts [hunk 1]
```diff
@@ -50,18 +50,19 @@ export default () => {
...
-            } else {
-                environmentAlias = await context.models.CmsEnvironmentAlias.findOne({
-                    query: { slug: context.cms.environment }
-                });
-                environment = await environmentAlias.environment;
-            }
-        }
 
-        if (!environment) {
+        try {
```
Comment (doitadrian) [inline packages/api-headless-cms/src/content/plugins/models.ts:54]: This won't work, because if the user passed an ID of unexisting env, line `57` would get executed, meaning `environment` would be `null` (`findById` will return `null`). After this, the next line we have is the `  context.cms.environment = environment.slug;`, which would again throw a mystery error to the user. :)

I'd stick with the proposition we discussed over the call:
image

**Comment by doitadrian** [comment]
Hoping we can merge this for the upcoming release. Let me know tomorrow if you'll have any questions.

Thanks @EmilK15
