### PR TITLE
Fix: Headless CMS - Rich Text Editor Max Height

### LINKED ISSUE #970: Headless CMS - Rich Text Editor Max Height
Let's set a max height on the editor, so that the editor doesn't expand too much, and toolbar icons don't get invisible.

With this issue, we could probably also solve this one: https://github.com/webiny/webiny-js/issues/933

### PR DESCRIPTION
**Pull request by Ashu96**
## Related Issue
Closes #970 #933 
Headless CMS - Rich Text Editor Max Height
## Your solution
- Fix content getting too tall that toolbar hide due to scroll, by adding `height` property
- Add resizer so that the user can resize the editor if needed

## How Has This Been Tested?
Manually, via the Admin app

## Screenshots:
image

### CODE REVIEW

File: packages/app-i18n/src/admin/components/RichTextEditor/RichTextEditor.tsx [hunk 1]
```diff
@@ -10,16 +10,24 @@ import { MenuButton } from "./index";
...
-import { Range, Descendant } from "slate";
 
 const EditorWrapper = styled("div")({
     border: "1px solid var(--mdc-theme-on-background)",
     borderRadius: 2,
     boxSizing: "border-box",
-    padding: 10
+    padding: 10,
+
+    "& > div:first-of-type": {
```
Comment (doitadrian) [inline packages/app-i18n/src/admin/components/RichTextEditor/RichTextEditor.tsx:20]: Let's go with this approach maybe:
image
