### PR TITLE
fix: fix pasting into paragraph/text editor component

### LINKED ISSUE #2346: [Page Builder] Pasting function pastes text at the beginning of the paragraph instead of new row
### Version

5.24.0

### Operating System

MacOS 12.2.1

### Browser

Chrome

### What steps will reproduce the bug?

1. In Page Builder, create a new page and add an element to it. 
(I've had this issue with Heading, Paragraph, List and Block quote elements).

2. Within the element, write some text then try to paste more text at the end of the sentence or in a new row. 

### What is the expected behavior?

The pasted text should be pasted in the current cursor position. 

### What do you see instead?

At the moment, the pasted text will be added at the very beginning of the text in the element. 

I've tried several options and found that: 

1. if the text is pasted after a blank space or a new row, the error will occur and the text will be added at the beginning of the paragraph. 

Situation A - one space added at the end of the sentence:
image

Result:
image

Situation B - new row added
image

Result:
image

2. If the text is pasted right after another character (without space or row break) it will be added correctly. 

Situation C - pasted without space or rowbreak
image

Result: 
image

### Additional information

_No response_

### Possible solution

_No response_

### PR DESCRIPTION
**Pull request by neatbyte-vnobis**
## Changes
Fix "Pasting function pastes text at the beginning of the paragraph instead of new row" bug.
Closes #2346

## How Has This Been Tested?
Manual

## Documentation
None

### CODE REVIEW

**Comment by SvenAlHamad** [comment]
This issue still seems to be present. The text is pasted always at the start of the paragraph, instead of where the current cursor is positioned. 

https://user-images.githubusercontent.com/3808420/199535373-a59b4db4-02b4-43ed-9545-8f7fb4690d65.mov

**Comment by SvenAlHamad** [comment]
Re-tested this one, and it's working fine now. I had an issue with my build command previously.

File: packages/app-page-builder/src/editor/components/Text/PbText.tsx [hunk 1]
```diff
@@ -59,7 +59,10 @@ const PbText: React.FC<TextElementProps> = ({ elementId, mediumEditorOptions, ro
         return null;
     }
 
-    const textContent = variableValue || get(element, `${DATA_NAMESPACE}.data.text`);
+    // only used to set initial value, so no reason to update it every time
```
Comment (adrians5j) [inline packages/app-page-builder/src/editor/components/Text/PbText.tsx]:
```suggestion
    // Stores only the initial content, so no reason to update on each render.
```

**Review by adrians5j — CHANGES_REQUESTED** [review]
Thanks for resolving this.

Although I had one nitpick before we merge. 🙂

File: packages/app-page-builder/src/editor/components/Text/PbText.tsx [hunk 2]
```diff
@@ -59,7 +59,10 @@ const PbText: React.FC<TextElementProps> = ({ elementId, mediumEditorOptions, ro
...
+    const textContent = useMemo(() => {
```
Comment (adrians5j) [inline packages/app-page-builder/src/editor/components/Text/PbText.tsx]: BTW, can we rename this variable then to `initialText`? That way even the comment would not be needed.

**Review by adrians5j — CHANGES_REQUESTED** [review]
Added one quick question.

File: packages/app-page-builder/src/editor/components/Text/PbText.tsx (hunk 2 above)
Comment (adrians5j) [reply packages/app-page-builder/src/editor/components/Text/PbText.tsx]: Also, this `useMemo` hook is used after the if statement that can potentially return `null` (check L59).

This hook usage should be relocated above the if statement.

Comment (neatbyte-vnobis) [reply packages/app-page-builder/src/editor/components/Text/PbText.tsx]: @adrians5j I have changed it according to a comment.
Also I have dropped `return` statement (to be in same style as `fallbackValue`)

**Review by adrians5j — APPROVED** [review]
Nice.
