### PR TITLE
Fix: field labels not shown for current locale

### LINKED ISSUE #1096: Headless CMS - field labels not shown for current locale
Changing the locale doesn't change the actual labels (we did set them in the field dialog).

image

### PR DESCRIPTION
**Pull request by Ashu96**
## Related Issue

Closes #1096 

## Your solution
Use `getValue` function from `useI18N` hook to get values like `label and description` for current locale.

## How Has This Been Tested?
Manually using the Admin app.

## Screenshots (if relevant):
https://www.loom.com/share/6144458813ec4d4dbb38693b464942de

### CODE REVIEW

File: packages/app-headless-cms/src/admin/plugins/fieldRenderers/dateTime/Time.tsx [hunk 1]
```diff
@@ -8,7 +8,7 @@ const Time = props => {
             {...props}
             field={{
                 ...props.field,
-                label: props.label
+                label: props.label || props.field.label
```
Comment (doitadrian) [inline packages/app-headless-cms/src/admin/plugins/fieldRenderers/dateTime/Time.tsx:11]: Why do we need both props.label && props.field.label? 🤔

Comment (doitadrian) [inline packages/app-headless-cms/src/admin/plugins/fieldRenderers/dateTime/Time.tsx:11]: Why do we need `props.label || props.field.label` ? 🤔

File: packages/app-headless-cms/src/admin/plugins/fieldRenderers/dateTime/dateTimeFields.tsx [hunk 2]
```diff
@@ -60,16 +62,21 @@ const plugin: CmsEditorFieldRendererPlugin = {
...
                                 />
                             );
                         }
 
                         return (
                             <Input
-                                {...bind.index}
+                                bind={{
+                                    ...bind.index,
+                                    label: t`Value {number}`({ number: index + 1 })
```
Comment (doitadrian) [inline packages/app-headless-cms/src/admin/plugins/fieldRenderers/dateTime/dateTimeFields.tsx:74]: `label` prop can't be passed to `bind`, am I missing something here?

File: packages/app-headless-cms/src/admin/plugins/fieldRenderers/file/fileField.tsx [hunk 3]
```diff
@@ -16,16 +16,25 @@ const plugin: CmsEditorFieldRendererPlugin = {
...
-                        <Label>
-                            <I18NValue value={field.label} />
-                        </Label>
-                        <Bind>{bind => <SingleFile field={field} bind={bind} />}</Bind>
+                        <Label>{label}</Label>
+                        <Bind>
+                            {bind => (
+                                <SingleFile
+                                    field={field}
+                                    bind={{ ...bind, description: helpText }}
```
Comment (doitadrian) [inline packages/app-headless-cms/src/admin/plugins/fieldRenderers/file/fileField.tsx:34]: `description` prop can't be passed to `bind`, am I missing something here?

**Review by adrians5j — CHANGES_REQUESTED** [review]
Please check my comments, maybe I'm missing something. 🤔

File: packages/app-headless-cms/src/admin/plugins/fieldRenderers/dateTime/Time.tsx (hunk 1 above)
Comment (Ashu96) [reply packages/app-headless-cms/src/admin/plugins/fieldRenderers/dateTime/Time.tsx:11]: `Time` component is used in two different places.

- As standalone `Time` field in case of `DateTime` format is set to `Time only`. The label is what we specify in `field settings`. 
- But, when `Time` is used to compose `DateTimeWithoutTimezone` and `DateTimeWithTimezone` it has label specified by that component. For example, if the field label is `sale ends` in the case of `DateTimeWithTimezone`, the label for `Time` field will be `sale ends time`.

Comment (Ashu96) [reply packages/app-headless-cms/src/admin/plugins/fieldRenderers/dateTime/Time.tsx]: I was doing something wrong. It doesn't have to be this way.
Thanks for the feedback @doitadrian :)

**Review by adrians5j — APPROVED** [review]
